/**
 * signer.ts — Global Signer Identity Management
 *
 * ══════════════════════════════════════════════════════════════════════
 * MULTI-COMPUTER COLLECTION ARCHITECTURE
 * ══════════════════════════════════════════════════════════════════════
 *
 *  GitHub repository  = shared application code (cloned identically on every computer)
 *  Browser localStorage = per-computer signer registry (private, never shared)
 *  Exported JSON      = portable dataset (sent to coordinator for merging)
 *  signer_id          = globally unique UUID — the merge-safe identity key
 *
 * ══════════════════════════════════════════════════════════════════════
 * ID GENERATION RULES
 * ══════════════════════════════════════════════════════════════════════
 *
 *  1. Every NEW signer receives an ID generated by crypto.randomUUID().
 *     Format: "signer_<UUID>"
 *     Example: "signer_550e8400-e29b-41d4-a716-446655440000"
 *
 *  2. The signer_id is stored in localStorage the moment it is created
 *     and reloaded on every subsequent session. Browser restarts do NOT
 *     create new IDs for existing signers.
 *
 *  3. The display name (signer_name) has NO influence on the signer_id.
 *     Two computers calling createSigner("Rohan") will produce two
 *     completely different signer_ids because each UUID is independently
 *     generated by the browser's cryptographically strong RNG.
 *
 *  4. Legacy IDs loaded from localStorage (e.g. "signer_A", "signer_005")
 *     are preserved as-is and are never migrated or renumbered.
 *
 *  5. Sequential numbering (signer_001, signer_002, ...) is NEVER used for
 *     new signers because it produces collisions across computers.
 */

export interface Signer {
  /** Globally unique identifier. Format: "signer_<UUID>" for new signers.
   *  Legacy signers retain their original format (e.g. "signer_A", "signer_005"). */
  id: string;
  /** Human-readable display name (e.g. "Rohan", "Amit"). Never influences the id. */
  name: string;
}

/** localStorage key used to persist the signer list. */
const STORAGE_KEY = "isl_signers";

/**
 * Pre-seeded default signers used in the original pilot collection.
 * These legacy IDs must never be replaced, renumbered, or migrated.
 */
export const DEFAULT_SIGNERS: Signer[] = [
  { id: "signer_A",     name: "Signer A" },
  { id: "signer_B",     name: "Signer B" },
  { id: "signer_C",     name: "Signer C" },
  { id: "smoke_tester", name: "Smoke Tester" },
];

/**
 * Generates a globally unique signer ID using the browser's
 * cryptographically strong random UUID generator.
 *
 * This function is only called when creating a BRAND-NEW signer.
 * It is never called to re-generate an ID for an existing signer.
 *
 * @returns A string of the form "signer_<UUID>"
 */
export function generateSignerId(): string {
  const uuid = crypto.randomUUID();
  return `signer_${uuid}`;
}

/**
 * Creates a new Signer object with a globally unique ID.
 *
 * The display name does NOT influence the ID in any way.
 * Two independent calls to createSigner("Rohan") — even on the same computer —
 * will produce two different signer_ids.
 *
 * @param name  Human-readable display name (will be trimmed).
 * @returns     A new Signer with a UUID-based id.
 */
export function createSigner(name: string): Signer {
  return {
    id: generateSignerId(),
    name: name.trim(),
  };
}

/**
 * Loads the signer list from localStorage.
 *
 * - If a saved list is found, it is returned as-is (legacy IDs preserved).
 * - If no saved list exists, DEFAULT_SIGNERS is returned.
 * - If localStorage is unavailable (SSR), DEFAULT_SIGNERS is returned.
 *
 * @returns Array of Signer objects, in the order they were added.
 */
export function loadSigners(): Signer[] {
  if (typeof window === "undefined") return [...DEFAULT_SIGNERS];
  try {
    const saved = localStorage.getItem(STORAGE_KEY);
    if (saved) {
      const parsed = JSON.parse(saved);
      if (Array.isArray(parsed) && parsed.length > 0) {
        return parsed as Signer[];
      }
    }
  } catch (e) {
    console.error("[SignerManager] Failed to load signers from localStorage:", e);
  }
  return [...DEFAULT_SIGNERS];
}

/**
 * Persists the current signer list to localStorage.
 * Call this after every mutation (add signer, etc.).
 *
 * @param signers  The complete, up-to-date list of signers.
 */
export function saveSigners(signers: Signer[]): void {
  if (typeof window === "undefined") return;
  try {
    localStorage.setItem(STORAGE_KEY, JSON.stringify(signers));
  } catch (e) {
    console.error("[SignerManager] Failed to save signers to localStorage:", e);
  }
}
